/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/path-params/s/simple/e/no/{array}/{enum}/{null}/{number}/{object}/{string}": {
    get: {
      parameters: {
        query: {
          number: components["parameters"]["query_form_explode_number"];
          enum: components["parameters"]["query_form_explode_enum"];
          array: components["parameters"]["query_form_explode_array"];
          null: components["parameters"]["query_form_explode_null"];
          object: components["parameters"]["query_form_explode_object"];
          string: components["parameters"]["query_form_explode_string"];
        };
        header: {
          enum: components["parameters"]["header_simple_enum"];
          number: components["parameters"]["header_simple_number"];
          array: components["parameters"]["header_simple_array"];
          null: components["parameters"]["header_simple_optional_null"];
          object: components["parameters"]["header_simple_object"];
          string: components["parameters"]["header_simple_optional_string"];
        };
        path: {
          enum: components["parameters"]["path_simple_enum"];
          number: components["parameters"]["path_simple_number"];
          array: components["parameters"]["path_simple_array"];
          null: components["parameters"]["path_simple_null"];
          object: components["parameters"]["path_simple_object"];
          string: components["parameters"]["path_simple_string"];
        };
      };
      requestBody: components["requestBodies"]["Default"];
      responses: {
        200: components["responses"]["BodyAndHeadersObject"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    parameters: {
      query: {
        number: components["parameters"]["query_form_explode_number"];
        enum: components["parameters"]["query_form_explode_enum"];
      };
      header: {
        enum: components["parameters"]["header_simple_enum"];
        number: components["parameters"]["header_simple_number"];
      };
      path: {
        enum: components["parameters"]["path_simple_enum"];
        number: components["parameters"]["path_simple_number"];
      };
    };
  };
  "/path-params/s/simple/e/yes/{array}/{enum}/{null}/{number}/{object}/{string}": {
    put: {
      parameters: {
        query: {
          number: components["parameters"]["query_form_explode_number"];
          enum: components["parameters"]["query_form_explode_enum"];
          array: components["parameters"]["query_form_explode_array"];
          null: components["parameters"]["query_form_explode_null"];
          object: components["parameters"]["query_form_explode_object"];
          string: components["parameters"]["query_form_explode_string"];
        };
        header: {
          enum: components["parameters"]["header_simple_enum"];
          number: components["parameters"]["header_simple_number"];
          array: components["parameters"]["header_simple_array"];
          null: components["parameters"]["header_simple_optional_null"];
          object: components["parameters"]["header_simple_object"];
          string: components["parameters"]["header_simple_optional_string"];
        };
        path: {
          enum: components["parameters"]["path_simple_explode_enum"];
          number: components["parameters"]["path_simple_explode_number"];
          array: components["parameters"]["path_simple_explode_array"];
          null: components["parameters"]["path_simple_explode_null"];
          object: components["parameters"]["path_simple_explode_object"];
          string: components["parameters"]["path_simple_explode_string"];
        };
      };
      requestBody: components["requestBodies"]["Default"];
      responses: {
        200: components["responses"]["BodyAndHeadersObject"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    parameters: {
      query: {
        number: components["parameters"]["query_form_explode_number"];
        enum: components["parameters"]["query_form_explode_enum"];
      };
      header: {
        enum: components["parameters"]["header_simple_enum"];
        number: components["parameters"]["header_simple_number"];
      };
      path: {
        enum: components["parameters"]["path_simple_explode_enum"];
        number: components["parameters"]["path_simple_explode_number"];
      };
    };
  };
  "/path-params/s/label/e/no/{array}/{enum}/{null}/{number}/{object}/{string}": {
    post: {
      parameters: {
        query: {
          number: components["parameters"]["query_form_explode_number"];
          enum: components["parameters"]["query_form_explode_enum"];
          array: components["parameters"]["query_form_explode_array"];
          null: components["parameters"]["query_form_explode_null"];
          object: components["parameters"]["query_form_explode_object"];
          string: components["parameters"]["query_form_explode_string"];
        };
        header: {
          enum: components["parameters"]["header_simple_enum"];
          number: components["parameters"]["header_simple_number"];
          array: components["parameters"]["header_simple_array"];
          null: components["parameters"]["header_simple_optional_null"];
          object: components["parameters"]["header_simple_object"];
          string: components["parameters"]["header_simple_optional_string"];
        };
        path: {
          enum: components["parameters"]["path_label_enum"];
          number: components["parameters"]["path_label_number"];
          array: components["parameters"]["path_label_array"];
          null: components["parameters"]["path_label_null"];
          object: components["parameters"]["path_label_object"];
          string: components["parameters"]["path_label_string"];
        };
      };
      requestBody: components["requestBodies"]["Default"];
      responses: {
        200: components["responses"]["BodyAndHeadersObject"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    parameters: {
      query: {
        number: components["parameters"]["query_form_explode_number"];
        enum: components["parameters"]["query_form_explode_enum"];
      };
      header: {
        enum: components["parameters"]["header_simple_enum"];
        number: components["parameters"]["header_simple_number"];
      };
      path: {
        enum: components["parameters"]["path_label_enum"];
        number: components["parameters"]["path_label_number"];
      };
    };
  };
  "/path-params/s/label/e/yes/{array}/{enum}/{null}/{number}/{object}/{string}": {
    delete: {
      parameters: {
        query: {
          number: components["parameters"]["query_form_explode_number"];
          enum: components["parameters"]["query_form_explode_enum"];
          array: components["parameters"]["query_form_explode_array"];
          null: components["parameters"]["query_form_explode_null"];
          object: components["parameters"]["query_form_explode_object"];
          string: components["parameters"]["query_form_explode_string"];
        };
        header: {
          enum: components["parameters"]["header_simple_enum"];
          number: components["parameters"]["header_simple_number"];
          array: components["parameters"]["header_simple_array"];
          null: components["parameters"]["header_simple_optional_null"];
          object: components["parameters"]["header_simple_object"];
          string: components["parameters"]["header_simple_optional_string"];
        };
        path: {
          enum: components["parameters"]["path_label_explode_enum"];
          number: components["parameters"]["path_label_explode_number"];
          array: components["parameters"]["path_label_explode_array"];
          null: components["parameters"]["path_label_explode_null"];
          object: components["parameters"]["path_label_explode_object"];
          string: components["parameters"]["path_label_explode_string"];
        };
      };
      requestBody: components["requestBodies"]["Default"];
      responses: {
        200: components["responses"]["BodyAndHeadersObject"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    parameters: {
      query: {
        number: components["parameters"]["query_form_explode_number"];
        enum: components["parameters"]["query_form_explode_enum"];
      };
      header: {
        enum: components["parameters"]["header_simple_enum"];
        number: components["parameters"]["header_simple_number"];
      };
      path: {
        enum: components["parameters"]["path_label_explode_enum"];
        number: components["parameters"]["path_label_explode_number"];
      };
    };
  };
  "/path-params/s/matrix/e/no/{array}/{enum}/{null}/{number}/{object}/{string}": {
    options: {
      parameters: {
        query: {
          number: components["parameters"]["query_form_explode_number"];
          enum: components["parameters"]["query_form_explode_enum"];
          array: components["parameters"]["query_form_explode_array"];
          null: components["parameters"]["query_form_explode_null"];
          object: components["parameters"]["query_form_explode_object"];
          string: components["parameters"]["query_form_explode_string"];
        };
        header: {
          enum: components["parameters"]["header_simple_enum"];
          number: components["parameters"]["header_simple_number"];
          array: components["parameters"]["header_simple_array"];
          null: components["parameters"]["header_simple_optional_null"];
          object: components["parameters"]["header_simple_object"];
          string: components["parameters"]["header_simple_optional_string"];
        };
        path: {
          enum: components["parameters"]["path_matrix_enum"];
          number: components["parameters"]["path_matrix_number"];
          array: components["parameters"]["path_matrix_array"];
          null: components["parameters"]["path_matrix_null"];
          object: components["parameters"]["path_matrix_object"];
          string: components["parameters"]["path_matrix_string"];
        };
      };
      requestBody: components["requestBodies"]["Default"];
      responses: {
        200: components["responses"]["BodyAndHeadersObject"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    parameters: {
      query: {
        number: components["parameters"]["query_form_explode_number"];
        enum: components["parameters"]["query_form_explode_enum"];
      };
      header: {
        enum: components["parameters"]["header_simple_enum"];
        number: components["parameters"]["header_simple_number"];
      };
      path: {
        enum: components["parameters"]["path_matrix_enum"];
        number: components["parameters"]["path_matrix_number"];
      };
    };
  };
  "/path-params/s/matrix/e/yes/{array}/{enum}/{null}/{number}/{object}/{string}": {
    head: {
      parameters: {
        query: {
          number: components["parameters"]["query_form_explode_number"];
          enum: components["parameters"]["query_form_explode_enum"];
          array: components["parameters"]["query_form_explode_array"];
          null: components["parameters"]["query_form_explode_null"];
          object: components["parameters"]["query_form_explode_object"];
          string: components["parameters"]["query_form_explode_string"];
        };
        header: {
          enum: components["parameters"]["header_simple_enum"];
          number: components["parameters"]["header_simple_number"];
          array: components["parameters"]["header_simple_array"];
          null: components["parameters"]["header_simple_optional_null"];
          object: components["parameters"]["header_simple_object"];
          string: components["parameters"]["header_simple_optional_string"];
        };
        path: {
          enum: components["parameters"]["path_matrix_explode_enum"];
          number: components["parameters"]["path_matrix_explode_number"];
          array: components["parameters"]["path_matrix_explode_array"];
          null: components["parameters"]["path_matrix_explode_null"];
          object: components["parameters"]["path_matrix_explode_object"];
          string: components["parameters"]["path_matrix_explode_string"];
        };
      };
      requestBody: components["requestBodies"]["Default"];
      responses: {
        200: components["responses"]["BodyAndHeadersObject"];
        401: components["responses"]["Unauthorized"];
        403: components["responses"]["Forbidden"];
        404: components["responses"]["NotFound"];
      };
    };
    parameters: {
      query: {
        number: components["parameters"]["query_form_explode_number"];
        enum: components["parameters"]["query_form_explode_enum"];
      };
      header: {
        enum: components["parameters"]["header_simple_enum"];
        number: components["parameters"]["header_simple_number"];
      };
      path: {
        enum: components["parameters"]["path_matrix_explode_enum"];
        number: components["parameters"]["path_matrix_explode_number"];
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    Number: number;
    Integer: number;
    String: string;
    Null: null;
    Boolean: boolean;
    Primitive: components["schemas"]["Boolean"] | components["schemas"]["String"] | components["schemas"]["Integer"] | components["schemas"]["Number"] | components["schemas"]["Null"];
    /** @enum {unknown} */
    Enum: "_1_" | "_2_" | "_3_";
    PrimitiveArray: (components["schemas"]["Primitive"])[];
    PrimitiveObject: {
      string: components["schemas"]["String"];
      number: components["schemas"]["Number"];
      integer?: components["schemas"]["Integer"];
      null?: components["schemas"]["Null"];
    };
    PrimitiveRecord: {
      [key: string]: components["schemas"]["Primitive"] | undefined;
    };
    DeepObject: {
      array?: components["schemas"]["PrimitiveArray"];
      record?: components["schemas"]["PrimitiveRecord"];
    };
    MediaTypeObjectApplicationJson: {
      /** @enum {unknown} */
      mediaType: "application/json";
      content?: components["schemas"]["PrimitiveObject"];
    };
    MediaTypeObjectApplicationXml: {
      /** @enum {unknown} */
      mediaType: "application/xml";
      content?: components["schemas"]["PrimitiveObject"];
    };
  };
  responses: {
    /** @description NOT_FOUND */
    NotFound: never;
    /** @description FORBIDDEN */
    Forbidden: never;
    /** @description UNAUTHORIZED */
    Unauthorized: never;
    /** @description OK */
    BodyAndHeadersObject: {
      headers: {
        "Content-Type": "application/json" | "application/xml";
      };
      content: {
        "application/json": components["schemas"]["MediaTypeObjectApplicationJson"];
        "application/xml": components["schemas"]["MediaTypeObjectApplicationXml"];
      };
    };
  };
  parameters: {
    path_simple_array: components["schemas"]["PrimitiveArray"];
    path_simple_explode_array: components["schemas"]["PrimitiveArray"];
    path_label_array: components["schemas"]["PrimitiveArray"];
    path_label_explode_array: components["schemas"]["PrimitiveArray"];
    path_matrix_array: components["schemas"]["PrimitiveArray"];
    path_matrix_explode_array: components["schemas"]["PrimitiveArray"];
    path_simple_enum: components["schemas"]["Enum"];
    path_simple_explode_enum: components["schemas"]["Enum"];
    path_label_enum: components["schemas"]["Enum"];
    path_label_explode_enum: components["schemas"]["Enum"];
    path_matrix_enum: components["schemas"]["Enum"];
    path_matrix_explode_enum: components["schemas"]["Enum"];
    path_simple_number: components["schemas"]["Number"];
    path_simple_explode_number: components["schemas"]["Number"];
    path_label_number: components["schemas"]["Number"];
    path_label_explode_number: components["schemas"]["Number"];
    path_matrix_number: components["schemas"]["Number"];
    path_matrix_explode_number: components["schemas"]["Number"];
    path_simple_null: components["schemas"]["Null"];
    path_simple_explode_null: components["schemas"]["Null"];
    path_label_null: components["schemas"]["Null"];
    path_label_explode_null: components["schemas"]["Null"];
    path_matrix_null: components["schemas"]["Null"];
    path_matrix_explode_null: components["schemas"]["Null"];
    path_simple_object: components["schemas"]["PrimitiveObject"];
    path_simple_explode_object: components["schemas"]["PrimitiveObject"];
    path_label_object: components["schemas"]["PrimitiveObject"];
    path_label_explode_object: components["schemas"]["PrimitiveObject"];
    path_matrix_object: components["schemas"]["PrimitiveObject"];
    path_matrix_explode_object: components["schemas"]["PrimitiveObject"];
    path_simple_string: components["schemas"]["String"];
    path_simple_explode_string: components["schemas"]["String"];
    path_label_string: components["schemas"]["String"];
    path_label_explode_string: components["schemas"]["String"];
    path_matrix_string: components["schemas"]["String"];
    path_matrix_explode_string: components["schemas"]["String"];
    header_simple_optional_array: components["schemas"]["PrimitiveArray"];
    header_simple_array: components["schemas"]["PrimitiveArray"];
    header_simple_explode_optional_array: components["schemas"]["PrimitiveArray"];
    header_simple_explode_array: components["schemas"]["PrimitiveArray"];
    header_simple_optional_enum: components["schemas"]["Enum"];
    header_simple_enum: components["schemas"]["Enum"];
    header_simple_explode_optional_enum: components["schemas"]["Enum"];
    header_simple_explode_enum: components["schemas"]["Enum"];
    header_simple_optional_number: components["schemas"]["Number"];
    header_simple_number: components["schemas"]["Number"];
    header_simple_explode_optional_number: components["schemas"]["Number"];
    header_simple_explode_number: components["schemas"]["Number"];
    header_simple_optional_null: components["schemas"]["Null"];
    header_simple_null: components["schemas"]["Null"];
    header_simple_explode_optional_null: components["schemas"]["Null"];
    header_simple_explode_null: components["schemas"]["Null"];
    header_simple_optional_object: components["schemas"]["PrimitiveObject"];
    header_simple_object: components["schemas"]["PrimitiveObject"];
    header_simple_explode_optional_object: components["schemas"]["PrimitiveObject"];
    header_simple_explode_object: components["schemas"]["PrimitiveObject"];
    header_simple_optional_string: components["schemas"]["String"];
    header_simple_string: components["schemas"]["String"];
    header_simple_explode_optional_string: components["schemas"]["String"];
    header_simple_explode_string: components["schemas"]["String"];
    query_form_optional_array?: components["schemas"]["PrimitiveArray"];
    query_form_array: components["schemas"]["PrimitiveArray"];
    query_form_explode_optional_array?: components["schemas"]["PrimitiveArray"];
    query_form_explode_array: components["schemas"]["PrimitiveArray"];
    query_spaceDelimited_optional_array?: components["schemas"]["PrimitiveArray"];
    query_spaceDelimited_array: components["schemas"]["PrimitiveArray"];
    query_spaceDelimited_explode_optional_array?: components["schemas"]["PrimitiveArray"];
    query_spaceDelimited_explode_array: components["schemas"]["PrimitiveArray"];
    query_pipeDelimited_optional_array?: components["schemas"]["PrimitiveArray"];
    query_pipeDelimited_array: components["schemas"]["PrimitiveArray"];
    query_pipeDelimited_explode_optional_array?: components["schemas"]["PrimitiveArray"];
    query_pipeDelimited_explode_array: components["schemas"]["PrimitiveArray"];
    query_form_optional_enum?: components["schemas"]["Enum"];
    query_form_enum: components["schemas"]["Enum"];
    query_form_explode_optional_enum?: components["schemas"]["Enum"];
    query_form_explode_enum: components["schemas"]["Enum"];
    query_form_optional_number?: components["schemas"]["Number"];
    query_form_number: components["schemas"]["Number"];
    query_form_explode_optional_number?: components["schemas"]["Number"];
    query_form_explode_number: components["schemas"]["Number"];
    query_form_optional_null?: components["schemas"]["Null"];
    query_form_null: components["schemas"]["Null"];
    query_form_explode_optional_null?: components["schemas"]["Null"];
    query_form_explode_null: components["schemas"]["Null"];
    query_form_optional_object?: components["schemas"]["PrimitiveObject"];
    query_form_object: components["schemas"]["PrimitiveObject"];
    query_form_explode_optional_object?: components["schemas"]["PrimitiveObject"];
    query_form_explode_object: components["schemas"]["PrimitiveObject"];
    query_deepObject_explode_optional_object?: components["schemas"]["PrimitiveObject"];
    query_deepObject_explode_object: components["schemas"]["PrimitiveObject"];
    query_form_optional_string?: components["schemas"]["String"];
    query_form_string: components["schemas"]["String"];
    query_form_explode_optional_string?: components["schemas"]["String"];
    query_form_explode_string: components["schemas"]["String"];
  };
  requestBodies: {
    Default?: {
      content: {
        "application/json": components["schemas"]["MediaTypeObjectApplicationJson"];
        "application/xml": components["schemas"]["MediaTypeObjectApplicationXml"];
      };
    };
  };
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
