export enum HttpStatus {
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  PROCESSING = 102,
  EARLYHINTS = 103,
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  AMBIGUOUS = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  PAYLOAD_TOO_LARGE = 413,
  URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  REQUESTED_RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  I_AM_A_TEAPOT = 418,
  MISDIRECTED = 421,
  UNPROCESSABLE_ENTITY = 422,
  FAILED_DEPENDENCY = 424,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
}

export const HttpStatusLabels = <const>{
  [HttpStatus.CONTINUE]: "continue",
  [HttpStatus.SWITCHING_PROTOCOLS]: "switching-protocols",
  [HttpStatus.PROCESSING]: "processing",
  [HttpStatus.EARLYHINTS]: "earlyhints",
  [HttpStatus.OK]: "ok",
  [HttpStatus.CREATED]: "created",
  [HttpStatus.ACCEPTED]: "accepted",
  [HttpStatus.NON_AUTHORITATIVE_INFORMATION]: "non-authoritative-information",
  [HttpStatus.NO_CONTENT]: "no-content",
  [HttpStatus.RESET_CONTENT]: "reset-content",
  [HttpStatus.PARTIAL_CONTENT]: "partial-content",
  [HttpStatus.AMBIGUOUS]: "ambiguous",
  [HttpStatus.MOVED_PERMANENTLY]: "moved-permanently",
  [HttpStatus.FOUND]: "found",
  [HttpStatus.SEE_OTHER]: "see-other",
  [HttpStatus.NOT_MODIFIED]: "not-modified",
  [HttpStatus.TEMPORARY_REDIRECT]: "temporary-redirect",
  [HttpStatus.PERMANENT_REDIRECT]: "permanent-redirect",
  [HttpStatus.BAD_REQUEST]: "bad-request",
  [HttpStatus.UNAUTHORIZED]: "unauthorized",
  [HttpStatus.PAYMENT_REQUIRED]: "payment-required",
  [HttpStatus.FORBIDDEN]: "forbidden",
  [HttpStatus.NOT_FOUND]: "not-found",
  [HttpStatus.METHOD_NOT_ALLOWED]: "method-not-allowed",
  [HttpStatus.NOT_ACCEPTABLE]: "not-acceptable",
  [HttpStatus.PROXY_AUTHENTICATION_REQUIRED]: "proxy-authentication-required",
  [HttpStatus.REQUEST_TIMEOUT]: "request-timeout",
  [HttpStatus.CONFLICT]: "confict",
  [HttpStatus.GONE]: "gone",
  [HttpStatus.LENGTH_REQUIRED]: "length-required",
  [HttpStatus.PRECONDITION_FAILED]: "precondition-failed",
  [HttpStatus.PAYLOAD_TOO_LARGE]: "payload-too-large",
  [HttpStatus.URI_TOO_LONG]: "uri-too-long",
  [HttpStatus.UNSUPPORTED_MEDIA_TYPE]: "unsupported-media-type",
  [HttpStatus.REQUESTED_RANGE_NOT_SATISFIABLE]:
    "requested-range-not-satisfiable",
  [HttpStatus.EXPECTATION_FAILED]: "expectation-failed",
  [HttpStatus.I_AM_A_TEAPOT]: "i-am-a-teapot",
  [HttpStatus.MISDIRECTED]: "misdirected",
  [HttpStatus.UNPROCESSABLE_ENTITY]: "unprocessable-entity",
  [HttpStatus.FAILED_DEPENDENCY]: "failed-dependency",
  [HttpStatus.PRECONDITION_REQUIRED]: "precondition-required",
  [HttpStatus.TOO_MANY_REQUESTS]: "too-many-requests",
  [HttpStatus.INTERNAL_SERVER_ERROR]: "internal-server-error",
  [HttpStatus.NOT_IMPLEMENTED]: "not-implemented",
  [HttpStatus.BAD_GATEWAY]: "bad-gateway",
  [HttpStatus.SERVICE_UNAVAILABLE]: "service-unavailable",
  [HttpStatus.GATEWAY_TIMEOUT]: "gateway-timeout",
  [HttpStatus.HTTP_VERSION_NOT_SUPPORTED]: "http-version-not-supported",
};
